### ISSUE TITLE
Request Mural access for Lynn and Belle

### ISSUE THREAD

**Issue by beckyphung** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#10]
### User story
As the PO, I need to request access to Mural for Belle and Lynn. They need their VA emails first. 

### Tasks
- [x] submit [DOTS request](https://jira.devops.va.gov/servicedesk/customer/portal/1)

### ACs
- [x] Belle can access Mural
- [x] Lynn can access Mural

### Links
- [Platform guidance](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-Mural) on requesting Mural access

**Comment by msbtterswrth** [comment]
this is great! confirmed we all  have access, and closing!
