### ISSUE TITLE
Discover Baseline for Current 508 and WCAG Compliance in patterns and components used on the VA.gov site

### ISSUE THREAD

**Issue by Jones-Morgan** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#14]
### Background 
In order to measure our successes, we need to establish a baseline for 508/WCAG compliance against which we can compare our future contributions. 

### ACs
- [x] Gain a measure of the current status of 508 and WGAC compliance

### Tasks
- [ ] ~~Test patterns with manual tools and document differences and justification for differences between USWDS and VADS~~ (this will be done for each individual design pattern as we pick it up)
- [x] Research documentation on current status 
- [ ] ~~Formulate a research plan for further research or testing~~ (this step will also get incorporated into each individual pattern that we adopt)

**Comment by Jones-Morgan** [comment]
I've updated this ticket and plan to resolve it with two caviats: 1. The testing task will be done on our end to ensure base level compliance which is: perfect accessibility scores per Section 508 and Web Content Accessibility Guidelines 2.2 requirements via automated and manual testing. I've updated the testing task with a link that gives instructions for manual testing.
2. The research plan for further testing may also involve the usability testing and so seems to overlap with other research tasks, but if it will be for accessibility testing it will be a preliminary task to the manual tests we do for any pattern we work on.

**Comment by Jones-Morgan** [comment]
My findings for this ticket revealed that the statement in our PWS is accurate and actually only indicates the bare minimum requirement for Veteran facing patterns/components. Beginning July 18th the VADS team is working on more transparent documentation on tests and finding for each pattern.
My resource for this information is Ryan Smith, who is one of the Accessibility Specialists on the VADS team.

**Comment by Jones-Morgan** [comment]
See my notes on from my discovery on this ticket in the spreadsheet: https://docs.google.com/spreadsheets/d/16kJQMVz5BoN8wfXhA1n84zPJh60zdSrCTH9Yjz-AVCQ/edit?gid=1772762838#gid=1772762838

**Comment by ChristineRoseSteiffer** [comment]
I agree with Morgan on the first and last AC for this ticket and have edited them accordingly.

**Comment by Jones-Morgan** [comment]
Here is my findings report: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design%20and%20Research/Accessibility/Accessibility%20Baseline.md
