### ISSUE TITLE
Mini Epic - updates to 22-1990 for review page prototype

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#170]
### User Story
As an engineer I need to make updates to our existing Orange task to continue work on the review page prototype.

### Background
There are lots of issues with added a different review page altogether to a form along with coupling it to a different editing flow and different form custom pages that also utilize the review InfoSection style of showing information.

From the initial ticket there was discovered lots of areas that need to be fully worked out, but this mini epic will house this laundry list to split into smaller tickets.

### Issues

Overall
- ensure that scroll to top and focus is correct for pages. Some pages get focused, but many pages keep scroll position and don't update focus

Intro page
- update sign in alert to redirect to loggedIn=true query string
- update header of sign in alert to match design

Applicant Information
- adjust spacing on 'We'll save your application on every change'
- Bold 'Note'
- Add text: "If you want to update your contact information for other VA benefits, you can do that from your profile."

Service Period
- Update for review InfoSection style design
- Figure out how adding and editing service periods would work and if editing removes all prefilled periods

Editing other contact info
- original prototype had other contact info being updated, and the newest iteration is using mailing address as the edit, so need to update this to work for that field. (it should really be updated to support any of the fields for future testing)
- while not 100% necessary for this isolated task, we should implement the session storage redirect to get the POC working for any field / this edit page from either the review page or the in form page. Right now it automatically redirects back to review page with update success shown
- make sure field validation is fired before save occurs
- cancel button needs to go somewhere, and prompt for confirmation of cancel?

Review page:
- add back button next to submit
- add accessible names to edit links of each section
- ensure that chapters, pages, and items render in appropriate semantic html. There are some issues where there is a definition list and regular unordered lists being used.
- format service period dates as friendly strings
- update stepper if possible to be final step (currently shows 4/5)
- reroute to pattern 2 landing page on submit?
- add statement of truth / replace privacy policy checkbox
- update need help section to match design

### ACs
- [ ] all updates are made, and were split into tickets for discrete units of work

### Review needed by

- [ ] VA Product Owner 
- [ ] Product Manager
- [ ] UX Research Team
- [ ] Engineering Team

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Reviewers have approved.
