### ISSUE TITLE
Mailing address edit subtask page, update field validation and cancel button

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#176]
### User Story
As an engineer I want the buttons to behave correctly when validation is incorrect or the cancel button 

### Background
- make sure field validation is fired before save occurs
- cancel button needs to go somewhere, most likely back to the previous page (the review page)

### ACs
- [x] buttons work as expected

### Review needed by

- [ ] VA Product Owner 
- [ ] Product Manager
- [ ] UX Research Team
- [ ] Engineering Team

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Reviewers have approved.

**Comment by adamwhitlock1** [comment]
We have updated the prototype here: https://noxious-monster-gjxjrxqrrgfqvw-3001.app.github.dev/mock-form-ae-design-patterns/2/task-orange/introduction?loggedIn=false

It now includes the correct mailing address update screen that can be accessed by clicking the edit button on the review screen. Once it is viewed, you can remove the zip code or remove any other required field and attempt to save the form to view form validation.

**Comment by msbtterswrth** [comment]
Looks like when you click the continue button on the contact info screen it takes you back to the personal info step, is that right @adamwhitlock1?

**Comment by adamwhitlock1** [comment]
ah yes @msbtterswrth that issue should be fixed in my next PR, which is about ready for review. I'll ping you on that one when it is merged and available on this codespace, but there is some funkiness with the routing for the form system and it can result in navigating backwards if things aren't just right. Thanks

**Comment by msbtterswrth** [comment]
Sounds good, I'll close this one out when that comes through <3

**Comment by adamwhitlock1** [comment]
The newest updates should be available now on https://noxious-monster-gjxjrxqrrgfqvw-3001.app.github.dev/mock-form-ae-design-patterns/2

I just spun it up so it should be live for 4 hours, but if you want we can also go over things on Monday to make sure its all validated.

![Image](https://github.com/user-attachments/assets/7b3ffc52-9622-402b-9e04-50b8cf784379)
