### ISSUE TITLE
AEDP Sprint #2 - July 2

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#18]
### Sprint Goal
- [x] Determine first two patterns to build (#5) 

### Other Priorities
- [x] Finish North Star Workshop (#9)
- [x] Schedule an account exp team meeting about patterns (#16)
- [x] Refine first pattern task (#17)
- [x] Determine kickoff and quarterly planning meetings with Becky
10:00
- [x] Schedule recurring ceremonies in VA Teams Cal
- [x] Define Baselines (#8) **STRETCH**
    - [x] Discover Baseline for Current 508 and WCAG Compliance in patterns and components used on the VA.gov site (#14)

### Completed Items from last sprint
- [x] Research Existing Patterns within AE (#4)

**Comment by msbtterswrth** [comment]
Becky, just shipping to you to signify sprint end, Should I go ahead and close or would you like to review first?

**Comment by beckyphung** [comment]
@msbtterswrth I'd like to review first before closing. Will do that now :)

**Comment by beckyphung** [comment]
This is good to close from my end. Two things:

- Question: Could you send me a list of the recurring ceremonies? I'd like to see what else besides sprint planning I could attend, at least in the beginning as we we're working on developing our first patterns. 
- Comment: I know we discussed 'Service history' as a less prioritized pattern to work on. How do you/the team expect this pattern to be able to be generalized for wider-use outside of VA?

**Comment by msbtterswrth** [comment]
We have the following recurring ceremonies:
- demo every second Wednesday at 4pm
- retro every second Thursday at 12pm
- sprint planning/refinement is currently one meeting (which may eventually split into two) every first Thursday at 2pm

Regarding the Service History pattern, we have had some discussions around whether service history should remain a pattern at all once prefill is completed, as we don't currently let Veterans edit this information on their profile because it comes directly from DoD. We will continue to explore this line of thought as this next sprint or two unfolds.

**Comment by beckyphung** [comment]
Thank you! I thought there were a lot more, so appreciate the quick list :). I'm fine with not going to retro for now, just going to demo/sprint planning. Just lmk if there are ever any actions you all need from me after retros. 

Good to know with service history. Keep me updated!
