### ISSUE TITLE
[Pattern] Help users to... Update prefilled information

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#22]
### Background
As a Veteran, I want to easily edit prefilled form information and have it save to my profile, so I can keep my profile up to date.

### Additional Notes

There are several different 'profiles' users can edit across the various VA platforms and products, with the main profile found at va.gov/profile. This is the profile we will be referring to.

During our research into the Prefill Form Data pattern, we discovered that users may find outdated profile data that has been prefilled and want to correct it, so as part of this pattern we will aim to provide an easy way to update that profile data when completing a prefilled form.

**NOTE:  We considered having this pattern be "review" or "confirm" and update, but ultimately decided that the viewing of the prefilled information belonged in the #17 pattern.**

### Hypothesis
This pattern will tie in closely with the [prefill form pattern](https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/17) and knowing where and how to update out of date information when forms are prefilled. 

We believe that creating a standardized method to update prefilled form information will help users to:
- update their prefilled information
- know where those updates were saved to
- understand why they can not update certain information

We believe this pattern should consist of:
- one or more content updates within existing components and guidance including:
    - messaging about how to edit a prefilled field
    - messaging about where your updates will save
    - messaging about how why fields are not editable online
- one or more updates to the visual user flow of editing a prefilled field

### ACs
- [x] The team has a shared, documented understanding of this pattern 
    - [x] what are our assumptions about the pattern
    - [x] how we plan to test them
- [x] Research Plan has been created and submitted
- [x] Designs have been created for our pattern
- [x] Pattern has been reviewed by DSC and a collab cycle staging review point
- [x] A pattern exists in VADS
    - [x] Code examples are provided
    - [x] Design resources are provided
    - [x] Governance is provided including mockups and content
- [ ] **STRETCH** Have at least two teams implement the pattern on VA.gov  
- [x] **STRETCH** The pattern has been submitted to USWDS for consideration
