### ISSUE TITLE
[Pattern] Navigate as an authenticated user

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#23]
### Background
As a Veteran, I want to have consistent navigation, so I can easily navigate between authenticated content/applications and the rest of VA.gov.

### Hypothesis
We believe that integrating authenticated experience navigation into the global navigation structures, including guidance, example code, and design resources, will:
- Promote consistency in how authenticated experience navigation is implemented across VA platforms
- Allow Veterans to easily find and access things like their profile, common tasks or applications and notifications.

### Additional Notes
This may be blocked by #20 and #19

### ACs
- [ ] A pattern exists in VADS
    - [ ] Code examples are provided
    - [ ] Design resources are provided
    - [ ] Governance is provided
