### ISSUE TITLE
[Pattern] Auto-save alert

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#24]
### Background
As a Veteran, I want to have be notified that my form was auto-saved so that I can be confident my information has been saved automatically while I'm entering it.

### Hypothesis
We believe that creating an auto-save alert pattern, including guidance, example code, and design resources, will:
- Inform Veterans that their application has been saved, the date it was last saved on, and the request ID #
- Improve trust in the VA platform

### Additional Notes
There may be [existing components or patterns within VADS](https://design.va.gov/components/form/autosave) that we can improve upon already.

### ACs
- [ ] A pattern exists in VADS
    - [ ] Code examples are provided
    - [ ] Design resources are provided
    - [ ] Governance is provided
