### ISSUE TITLE
Epic - IIR team and prefill pattern adoption in forms-system

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#259]
## User Story
As an engineer I would like to help the IIR team adopt and implement the [Know when their information is prefilled](https://design.va.gov/patterns/help-users-to/know-when-their-information-is-prefilled) pattern.

## Background
The IIR team recently [worked on a feature](https://github.com/department-of-veterans-affairs/vets-website/pull/24213) to create a new form flow for newly authenticated Veterans to fill out their profile information. While building this feature they implemented prefill following an outdated contact list and loop pattern found in the [platform docs here](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-create-the-contact-info-ar).

This current implementation lives in the forms-system codebase and can be used in any form during the form flow.

**Relevant slack convos**
[Slack thread 1](https://dsva.slack.com/archives/C07909N7U8Z/p1733948971454949)
[Slack thread 2](https://dsva.slack.com/archives/C07909N7U8Z/p1733951221827169)

## Discovery Goals
- [x] Figure out how we would adapt the pattern into the forms-system code
- [x] Formulate a plan to incrementally adopt the changes into the code
- [ ] Evaluate the scope of the impacts that changes to this shared code would create

## Questions to Answer
- How can we add our pattern to the codebase and not break existing usage while in active development?
- How will the edge cases like missing information be handled?
- How do alerts related to missing info get displayed?

## Deliverables

- [ ] ticket in platform docs repo
- [ ] update prefill alert content component

## Acceptance Criteria
- [ ] platform task has been opened
- [ ] we've met with the platform docs team to talk about our updates

### Review needed by

- [ ] VA Product Owner 
- [ ] Product Manager
- [ ] UX Research Team
- [ ] Engineering Team

### Definition of Done

- [ ] Documentation has been updated, if applicable.
- [ ] Acceptance Criteria in related issue are met.
- [ ] Reviewers have approved.

**Comment by msbtterswrth** [comment]
We've broken this up into several subtasks, with the only remaining task currently open to update the documentation in VADs
