### ISSUE TITLE
[Pattern] Service History

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#27]
### Background
As a team member utilizing the USWDS, I want to have a standard pattern relating to a user's service history so that users can have a seamless experience across digital agencies.

### Hypothesis
We believe that the existing pattern for service history found in VADS, including guidance, example code, and design resources, will:
- Promote consistency in how and when users are asked about their service history across government agencies
- Improve trust in government services by creating a unified experience

### ACs
- [ ] A pattern exists in VADS
    - [ ] Code examples are provided
    - [ ] Design resources are provided
    - [ ] Governance is provided
