### ISSUE TITLE
[EPIC] AEDP 2024 Q4

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#3]
### Objective
In order to understand the scope of the AEDS project, In the first quarter we need to 
- create a common understand of what a pattern is
- research and document existing patterns within Authenticated Experiences and where, if any, opportunities exist to add new patterns.

**What is a pattern?**
A pattern will consist of:
- Code for web components and Hypertext Markup Language (HTML) templates
- Research documentation supporting the pattern’s success with users of VA.gov
- Validation against other Agency needs through a quarterly cross-agency workshop, to be facilitated by VA staff

### Business Outcomes this satisfies from [VA PO mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719240863056/54e2c8569725a72e996ae9b2a687867f572f4051?sender=29eb2bcc-d6c0-41e5-bc30-31269b58bd41)
- Research findings are made available to VA staff via OCTO’s standard research archiving processes
- Documentation for personalization patterns is authored for use and delivered to necessary stakeholders for integration into both https://design.va.gov and https://designsystem.digital.gov
- Research findings are delivered that are associated with testing personalization patterns with actual users, including:
    - Veterans
    - Veteran family members
    - VA staff
    - relevant members of the public

### ACs
- [ ] Baselines have been established (#8)
- [ ] TBD Pattern has been delivered
- [ ] TBD Pattern has been delivered

**Comment by msbtterswrth** [comment]
converting to milestones and closing
