### ISSUE TITLE
Baseline research of what prefill patterns exist

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#31]
### Background
As a AEDP team member I want to understand where and when prefill patterns exist within VA Authenticated Experiences across the platform/products and how they are used so that I can better document and improve the pattern for contribution to USWDS.

### Additional information
Potentially sync with governance team (collab cycle) and/or CAIA

### ACs
- [x] Current pattern locations are identified and documented #33
- [ ] Current patterns are tested for usability #34
- [ ] Findings are presented to relevant teams #35

**Comment by beckyphung** [comment]
Some questions from me:
- I see this is in the current sprint. Is this really for the next sprint (7/16 to 7/30)?
- In sprint #2, have we done a review of past research conducted already on prefill? I think that would inform additional research we'd want to conduct.

**Comment by ChristineRoseSteiffer** [comment]
I think the second two ACs are now for other tickets @msbtterswrth

**Comment by msbtterswrth** [comment]
yes they were @ChristineRoseSteiffer, good catch. Can you and @Jones-Morgan please add your points to this task?

**Comment by ChristineRoseSteiffer** [comment]
I think the other three are fine, although based on our design roadmap I might edit #34 to cover creating documentation for our first round of research, and we might need another ticket for creating design variations to include in the test.
