### ISSUE TITLE
Discover and Evaluate Options for Hosting Experimental 'Pre-fill' Pattern Work

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#32]
### Background
As an engineer on the auth patterns team, I want to identify and evaluate the best place to host our 'pre-fill' pattern work, so that we can efficiently develop, test, and iterate on this pattern without disrupting our main codebase.

### Tasks

1. Review and document the pros and cons of each potential hosting option:
   - vets-website _mock-form folder
   - Local vets-website repo branch with tunneling (Ngrok)
   - Online code prototyping tools (CodePen, CodeSandbox)
   - Separate repo with static site deployment (Netlify, GitHub Pages)
2. Investigate and document available tunneling solutions (if local option is considered viable)
  - [Ngrok](https://ngrok.com)
  - [PageKite](https://pagekite.net/)
  - [Localtunnel](https://theboroer.github.io/localtunnel-www)
  - others?
3. Set up proof-of-concept implementations in at least two of the most promising options
4. Evaluate each option based on:
   - Ease of setup and maintenance
   - Collaboration capabilities
   - Integration with existing workflows
   - Ability to mimic prod environment
5. Make recommendations and suggested next steps

### Acceptance Criteria

- [x] Brief document comparing all considered options is produced
- [x] At least two proof-of-concept implementations are created, but can be very minimal mvps
- [x] A recommendation is made, and is justified with information on how it will support our pattern development and testing
- [x] Potential risks or limitations of the recommended approach are identified and addressed
- [x] A plan for implementing the chosen solution is outlined / further tickets are created

**Comment by bellepx0** [comment]
Adam and I met today to discuss our initial findings for each of the 4 hosting options. Link to discovery doc [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/authenticated-patterns/discovery-work)
**Next steps:** 
Belle
* Develop Proof-of-Concept for port forwarding (tunneling) alongside using `yarn watch` method to point to vets-api staging (instead of localhost:3000 for vets-api).
* Develop Proof-of-Concept for creating a new application under "_mock-form" in the vets-website repo. 

Adam
* Develop Proof-of-Concept for using CodePen as an option

**Comment by adamwhitlock1** [comment]
I created this document outlining the pros and cons of working on pattern prototypes in Codepen:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/Codepen-notes.md

**Comment by adamwhitlock1** [comment]
Further work has been created in these tickets:

https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/51

https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/52

https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/53

https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/54

**Comment by adamwhitlock1** [comment]
Okay, I am going to close this now.

We have our main doc here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/engineering/%2332-Discover%20and%20Evaluate%20Options%20for%20Hosting%20Experimental%20'Pre-fill'%20Pattern%20Work.md which includs pros, cons, and all conclusions.
