### ISSUE TITLE
 Create Research Study Documentation Draft

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#34]
### Background
As a AEDP team member I want create document before planning a usability study to that we can improve the prefill pattern.

### ACs
- [x] A research plan draft exists
- [x] A conversation guide draft exists
- [x] A recruiting screener draft exists
### Tasks
- [x] Compilation of existing research
```

**Comment by Jones-Morgan** [comment]
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1721244474954/caac99516209e8112055cd58d858c8e279552337?sender=u649de617cef06172cf5f0271

**Comment by Jones-Morgan** [comment]
Here is a link to the folder that contains our research documentation drafts.
