### ISSUE TITLE
AEDP Sprint #3 - July 16

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#36]
### Sprint Goal
- [x] Create Research Study Documentation #34
- [x] Discover and Evaluate Options for Hosting Experimental 'Pre-fill' Pattern Work #32 

### Other Priorities
- [x] Current pattern locations are identified and documented #33
- [x] Current profile patterns are identified and documented #37 
- [ ] Create design variations #35
- [x] feedback mural #38
- [x] medallia responses investigation #39

### Team Capacity
- Christine Out  7/18-22
- Morgan out 7/22 + 7/29-Aug 3

### Completed Items from last sprint
- [x] Determine first two patterns to build (#5) 🎉 
- [x] Finish North Star Workshop (#9)
- [x] Schedule an account exp team meeting about patterns (#16)
- [x] Refine first pattern task (#17)
- [x] Determine kickoff and quarterly planning meetings with Becky
- [x] Schedule recurring ceremonies in VA Teams Cal

**Comment by beckyphung** [comment]
Some questions from me:
- I see this is in the current sprint. Is this really for the next sprint (7/16 to 7/30)?
- In sprint # 2, have we done a review of past research conducted already on prefill? I think that would inform additional research we'd want to conduct.

**Comment by ChristineRoseSteiffer** [comment]
Hey @beckyphung - for your second question, ticket #31 will cover our research into both where the existing prefill pattern exists in the codebase and what tests have been run on it previously. I agree that both of those will help to inform our next study.

**Comment by msbtterswrth** [comment]
@beckyphung Yes this is for Sprint 3, beginning today. Main goals of this sprint are to document the current prefill usage as @ChristineRoseSteiffer mentioned (on the UX side) and determine where our code will live and how we'll interact with VADS repos (on the eng side). 

We have a sprint planning later today at 4pm EST to align the team to make sure everything is accomplishable :)

**Comment by msbtterswrth** [comment]
@beckyphung sprint 3 is ended and ready for your review! We'll have demo tomorrow, if you want to wait until then to close out this task!

**Comment by beckyphung** [comment]
@msbtterswrth Thanks Lynn. I added a question to #39.
> @msbtterswrth Should this issue be reopened again, since @Jones-Morgan had issues with the original request? Not sure if the results from the second request have made it to Morgan yet
