### ISSUE TITLE
Submit user research and recruiting tasks

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#41]
### Background 
We need to submit our research plan and user recruiting tasks by Friday Aug 9th.

### AC

```[tasklist]
### Tasks
- [x] Submitting Research and Recruiting tickets
- [x] Research plan has been reviewed by OCTO Research team
- [x] Address feedback and update accordingly
```

**Comment by ChristineRoseSteiffer** [comment]
[Research review ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/650)
[Recruiting ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/649)

Both submitted Monday, Aug 19th.

**Comment by ChristineRoseSteiffer** [comment]
Shane approved our [ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/650) today and has passed it onto Perigean to begin recruiting. He requested some minor edits to the research plan to include the email addresses of our potential observers, which I made before confirming with him that they were added.

**Comment by msbtterswrth** [comment]
Great work, looks like we've accomplished all our tasks here, the study is scheduled and we're ready to go!
