### ISSUE TITLE
AEDP Sprint #4 - July 30

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#44]
### Sprint Goal
- [ ] Finalize Research Plan #46

### Other Priorities
- [ ] Set up intro call with Perigean #45
- [x] Synthesize Medallia survey feedback on 'Prefill' #48
- [x] FE Prefill Pattern - Control scenario 1010EZ aka Task 1 aka GREEN #51
- [ ] FE Prefill Pattern - Build variation 1 - 1010EZ Modified #52
- [x] BE Prefill Pattern - Add prefill model to vets-api #54
- [x] Discover what the "Help users to... Review and update prefilled information" pattern is #55
- [ ] Determine what we're testing and how #56
- [ ] FE Prefill Pattern - Build Variation 2 - 10182 form #53 (stretch)
- [ ] User study prep work #42 (stretch)

### Team Capacity
- Morgan OOO 7/29 - 8/2
- Christine OOO 7/31, 8/9 (half day), 8/13
- Belle OOO 8/9, 8/12
- Adam OOO 8/9
- Lynn OOO 8/9 (half day)

### Completed Items from last sprint
- [x] Create Research Study Documentation #34
- [x] Discover and Evaluate Options for Hosting Experimental 'Pre-fill' Pattern Work #32 
- [x] Current pattern locations are identified and documented #33
- [x] Current profile patterns are identified and documented #37 
- [ ] Create design variations drafts #35
- [x] feedback mural #38
- [x] medallia responses investigation #39

**Comment by msbtterswrth** [comment]
Based on risks with completing all prototypes before sprint end, replacing sprint goal of #41 with #46 and targeting #41 for completion 8/16.

**Comment by beckyphung** [comment]
Thanks @msbtterswrth. Two requests: 
- Can you add the titles of the tickets in this descriptions, so I don't have to click into each ticket to know what we're working on? 
- Can you make sure the team adds updates at least daily, so I understand what work is being done? It's not clear to me what's at risk of being completed this sprint vs. not completed based on the tickets because there aren't any updates in them

**Comment by beckyphung** [comment]
@msbtterswrth This was _before_ this morning's meeting, so that's why this is confusing. For the second bullet, I'd revise it to be: 
- Make sure updates added to tickets enough to understand what the current status of work is, any relevant artifacts/documents, blockers we're working through, etc. Doesn't have to be daily.

**Comment by msbtterswrth** [comment]
thanks for the clarification @beckyphung <3

**Comment by msbtterswrth** [comment]
Sprint's officially closed and everything that's pushed has been moved to the next sprint, please review/close unless you have any additional questions @beckyphung :)

**Comment by beckyphung** [comment]
@msbtterswrth Thanks for letting me know. I added some questions to some of the open issues from this sprint that were moved to the next one. Can you answer those q's/do any follow-up tasks before I close this sprint?

**Comment by beckyphung** [comment]
@msbtterswrth I'm going to go ahead and close this sprint, since we're working through the questions I added in our current issues right now.
