### ISSUE TITLE
BE Prefill Pattern - Add prefill model to vets-api

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#54]
## Issue Description
As a developer I need to provide prefill data to the staging environment for use in the mock form patterns that research is being conducted on.

## Tasks
- Follow the docs here: https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-work-with-pre-fill#VAFormsLibrary-HowtoworkwithPre-Fill-Vets-APIWork to add prefill data to the vets-api and deploy this to staging
- Include, name, ssn, file number, date of birth and contact info (phone, email, address). Possibly add other info like gender to have it available if and when other pattern work uses that data.
- Verify that data is present on staging and is prefilled into the form

## Acceptance Criteria
- [x] Prefill data is available in staging
- [x] Unit tests are created to make sure vets-api is covered
- [x] Prefill works in staging on the mock form app for basic info needed for research sessions

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

**Comment by adamwhitlock1** [comment]
The last PR that updated the formId has been merged into main and is available in staging. We can now see that the prefill / save in progress data is available. I have validated the prefill data with user 226. Below is a screenshot with the current state of the mock form along with the data being returned from the api endpoint.

Steps to validate view functionality are:

- Log in as test user
- View mock form url at https://staging.va.gov/mock-form-ae-design-patterns
- If the form shows that it is in progress, you can see use the "Start a new application" button to spool up a new instance of the form.


![Image](https://github.com/user-attachments/assets/ad343d22-30cb-4e43-87f0-54dda614d0e8)


Here is an example of the prefill data coming in from the api endpoint:
![Image](https://github.com/user-attachments/assets/f0ad4bbb-8e9c-4a2b-add1-57db6d9ec6a4)


This ticket can be closed now. Within task #51 Adam will make sure that the SSN is pulled into the form, as it is returned from the api, but just not mapped to the form field currently.

**Comment by msbtterswrth** [comment]
Looks great, TY!
