### ISSUE TITLE
Finalize Research Plan

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#62]
### User Story
As a member of the AEDP team I want to finalize our research plan so that we can submit it for review and scheduling.

### ACs
- [x] Research plan is ready for final review
- [x] Conversation guide is ready for final review
- [x] Screener questions are ready for final review
- [x] Research plan in it's entirety has been presented to the team

#### Artifacts - (Google docs links for now until the test plan has been reviewed by Matt & Becky on Friday)
[Research Plan](https://docs.google.com/document/d/1FpJjHwz0QPr1BR3QT6WksbZNlXSstIwoNAqJQVPoERE/edit)
[Conversation Guide](https://docs.google.com/document/d/13F01dD23dpAPWSK0RRiYXRa6_bw4QaoZk6BgsIqP1W0/edit) 

**Testing Plan:**

**Task Orange**
The unauthenticated signin alert
Header not included in prefill alerts
(Something about the language we use for non-editable data - awaiting CAIA response)
Prefilled information in the new “review style” for both editable and locked data
Users only save changes to the form
Service history presented in new “review style”
Review page and editing from there
Edit page contains multiple items 

**Task Gray**
Header not included in prefill alerts
(Something about the language we use for non-editable data - awaiting CAIA response)
Prefilled information (address, specifically) presented in new white review card for both editable and non-editable data
Only allow users to save to their profile
Service history presented in white review card style

**Task Blue**
Header included in prefill alerts
(Something about the language we use for non-editable data - awaiting CAIA response)
Prefilled information (address, specifically) presented in gray card for locked data and white review card for editable data
Allow users to choose if they save to their profile or only the form (default to their profile)
Edit page contains one item

**Comment by ChristineRoseSteiffer** [comment]
The research plan is ready for PO review. We met today and decided to remove Service History from the study, as we believe it's specific use case relates more to the 'Help users to understand when their data is mismatched' pattern that we will work on in the future. There are a few items to finalize, but they can be covered in our ticket next sprint for the review/revisions of the documentation and designs.

**Comment by beckyphung** [comment]
@ChristineRoseSteiffer and @kristen101606 I added some comments, suggestions, and q's!

**Comment by beckyphung** [comment]
@ChristineRoseSteiffer and @kristen101606 I reviewed the conversation guide. The biggest feedback I have is to add in the "Things to notice" section after asking questions. This clarifies the purpose of the questions. Thanks!
