### ISSUE TITLE
Finalize Conversation Guide + Screener Questions

### ISSUE THREAD

**Issue by ChristineRoseSteiffer** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#83]
The conversation guide and screener questions for our upcoming research study need to be finalized after conducting a pre-pilot study to determine how many tasks we will have each participant complete.

```[tasklist]
### Tasks
- [x] Convo guide draft is finalized
- [x] Convo guide draft is reviewed by Christine, Lynn & Becky
- [x] Pre-pilot study is completed on Thursday, Aug 15
- [x] Final edits are made to convo guide and screener questions
- [x] Convo guide added to va.gov-team repo
```

**Comment by beckyphung** [comment]
I'll review the conversation guide by EOD today @Jones-Morgan

**Comment by beckyphung** [comment]
I reviewed mostly everything except the specific flows section. I'll review that tomorrow. I let Morgan know [in this Slack thread](https://dsva.slack.com/archives/C07909N7U8Z/p1723570018786279).

**Comment by ACParker89** [comment]
@ChristineRoseSteiffer @Jones-Morgan Dropping the drafts revised conversation guide and the original here for us to iterate on after the pre-pilot session 

Revised draft: https://docs.google.com/document/d/1ALzw-a0c5bj7YTxEXg1NuQdW1HlWsqgSVHeqzsI_tx0/edit#heading=h.v9gch574tdxu

Original draft: https://docs.google.com/document/d/1hnJfa-jPCnYSKXENaWp81ailvdKh9mGnHuiJvukkCd8/edit?usp=sharing

We will do an overall review/sync/cleanup after the pre-pilot with our collective notes! 

CC: @beckyphung @msbtterswrth

**Comment by beckyphung** [comment]
I started adding notes to the revised draft. I'll finish reviewing the rest of the revised draft tomorrow. Looking good!

**Comment by beckyphung** [comment]
I finished reviewing the conversation guide and left some comments/suggestions

**Comment by ChristineRoseSteiffer** [comment]
This ticket is done - we've finalized the [convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/authenticated-patterns/Design%20and%20Research/2024-07-Research%20Initiative-One-Prefill/Prefill%20Research%20Study%20Convo%20Guide%2008_19_24.md) in the research repo and submitted our ticket.
