### ISSUE TITLE
Create Research Doc Templates

### ISSUE THREAD

**Issue by Jones-Morgan** [department-of-veterans-affairs/tmf-auth-exp-design-patterns#89]
```[tasklist]
### Tasks
- [x] Create conversation guide template from current convo guide for prefill research
- [x] Create research plan template from current research plan for prefill research
- [x] create mural template for research study
- [x] templates have been reviewed by the team
```

**Comment by msbtterswrth** [comment]
@ACParker89 @ChristineRoseSteiffer can you take a look at these templates and lmk if they're good to go or we should make any updates?

**Comment by ChristineRoseSteiffer** [comment]
I have reviewed these links and the templates all look good to me. I made some edits to the research plan template, but otherwise everything else looked good. I think this ticket can be closed!

**Comment by beckyphung** [comment]
This looks good to me! Thanks for linking the templates @msbtterswrth. Moving this to closed.
